### ISSUE TITLE
Import force interaction parameters into modular_furniture

### ISSUE THREAD

**Issue by alecive** [ScazLab/baxter_collaboration#13]
As per title, the force interaction parameters (and possibly others) should be present into `modular_action_provider.launch` as well. 

Cc @sarah-widder

**Comment by sarah-widder** [comment]
Should the `internalRecovery` parameter be added as well? `flatpack_furniture.launch` and `tower_building.launch` both have that as well as `speechPopUpDuration` if we will need either of those for the modular furniture. cc @alecive

**Comment by alecive** [comment]
I would say so. And I would set `internalRecovery` to true by default.

**Comment by alecive** [comment]
Fixed by #16
