### ISSUE TITLE
Improving and creating unit tests

### ISSUE THREAD

**Issue by sarimabbas** [ScazLab/baxter_collaboration#40]
### Checklist
* /baxter_collaboration_lib/src/robot_utils
	- [x] utils.cpp
	- [ ] baxter_trac_ik.cpp
	- [x] ros_thread_image.cpp

* /baxter_collaboration_lib/src/robot_interface
	- [ ] robot_interface.cpp
	- [ ] arm_ctrl.cpp
	- [x] gripper.cpp
	
* /baxter_collaboration_lib/src/robot_perception
	- [ ] aruco_client.cpp
	- [ ] cartesian_estimator.cpp
	- [ ] cartesian_estimator_client.cpp
	- [ ] cartesian_estimator_hsv.cpp

**Comment by alecive** [comment]
Closing because it is almost one year old! Thanks @sarimabbas for the help in this.
