### ISSUE TITLE
Improve the gripper class

### ISSUE THREAD

**Issue by alecive** [ScazLab/baxter_collaboration#5]
Right now, we have a semi-working situation with the vacuum gripper (i.e. it works, but we didn't have time to code it properly). It would be nice to fully port the sw to a robust scenario.

**Comment by alecive** [comment]
Features: 

 * Should work for both grippers
 * One interface for both grippers
 * Calibrate the gripper if it is not calibrated on startup (the feature is already present, but please do not change this)

**Comment by alecive** [comment]
@sarimabbas @akrzywosz just realized that there already is a gripper tester into `baxter_tictactoe`. You can try to move that file out from the tictactoe repo and start working on that if you want.

**Comment by sarimabbas** [comment]
ok will take a look :+1:

**Comment by sarimabbas** [comment]
For reference:
Pull request https://github.com/ScazLab/baxter_collaboration/pull/54:
* fixes the suction timeout error
* ports over methods from the python SDK with some abstraction
* works with a gripper keyboard utility

**Comment by alecive** [comment]
Fixed by #54
