### ISSUE TITLE
Remove ROSThread and ROSThreadObject altogether from the repository

### ISSUE THREAD

**Issue by alecive** [ScazLab/baxter_collaboration#51]
As per title

**Comment by sarimabbas** [comment]
Ref: https://github.com/ScazLab/baxter_collaboration/pull/53

**Comment by alecive** [comment]
Fixed with #53

**Comment by alecive** [comment]
@sarimabbas did this affect `baxter_tictactoe`and `baxter_react_controller` in any way?

**Comment by sarimabbas** [comment]
I'll just check

**Comment by sarimabbas** [comment]
No I was not able to find references to ros_thread or ros_thread_image in either repository (I searched for "thread"). However, I did see that in CMakeLists.txt of baxter_tictactoe (https://github.com/ScazLab/baxter_tictactoe/blob/master/CMakeLists.txt) on line 30, it says it needs boost::thread? Would this still be required?

**Comment by alecive** [comment]
I feel it can be removed. Try to remove it , and if it compiles, just push :)
